version: "3.3"
services:
    postgres:
      build: PostgreSQL/.
      container_name: db
      restart: always
      ports:
        - 5432:5432
      volumes:
        - .data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - DB_SSLMODE = disable

    webapp:
          build: WebApp/.
          container_name: webapp
          restart: always
          ports:
            - 8080:8080
          depends_on:
            - postgres
          environment:
            - POSTGRES_HOST = postgres
            - POSTGRES_USER = root
            - POSTGRES_PASSWORD = root
            - DB_SSLMODE = disable